/**
 * 채널별 page.evaluate() 추출 스크립트 — 원본 reference/contents-finder/finder/collectors/*.py 의 JS 를 그대로 옮긴 것입니다.
 * (파이썬 문자열 값을 그대로 직렬화해 옮겨 한 글자도 다르지 않음). 화면 구조가 바뀌면 여기 선택자를 고치고
 * `npm run channels:check` 로 확인하세요. 테스트(tests/channels-collectors.test.ts)는 이 문자열을 픽스처 HTML 에 그대로 실행합니다.
 */

export const NAVER_HOME_FEED = "() => {\n  const seen = new Map();\n  const nodes = [...document.querySelectorAll('[data-title][data-url]')];\n  nodes.forEach((el, order) => {\n    const url = el.getAttribute('data-url') || '';\n    const title = (el.getAttribute('data-title') || '').replace(/\\s+/g, ' ').trim();\n    if (!url || !title || seen.has(url)) return;\n    const card = el.querySelector('.chf_feed_card') || el.closest('.chf_feed_card');\n    let time = '', pages = '';\n    if (card) {\n      const urls = new Set([...card.querySelectorAll('[data-url]')].map(x => x.getAttribute('data-url')));\n      if (urls.size <= 1) {\n        const t = card.querySelector('.chf_text'); time = t ? t.innerText.trim() : '';\n        const p = card.querySelector('.chf_mw_page'); pages = p ? p.innerText.trim() : '';\n      }\n    }\n    const rk = parseInt(el.getAttribute('data-nlog-imp-rank') || '', 10);\n    seen.set(url, {\n      url: url, title: title,\n      service: el.getAttribute('data-service') || '',\n      clip: el.getAttribute('data-is-clip') === 'true',\n      channel: el.getAttribute('data-channel') || '',\n      channel_url: el.getAttribute('data-channel-url') || '',\n      cid: el.getAttribute('data-cid') || '',\n      time: time, pages: pages, imp_rank: isNaN(rk) ? null : rk, order: order,\n    });\n  });\n  return [...seen.values()];\n}";

export const NAVER_RANKING_ENTERTAIN = "() => [...document.querySelectorAll('li[class*=\"NewsItem_news_item\"]')].map((li, i) => {\n  const a = li.querySelector('a[href*=\"/article/\"]');\n  const t = li.querySelector('[class*=\"NewsItem_title\"]');\n  const v = li.querySelector('[class*=\"NewsItem_view\"]');\n  const d = li.querySelector('[class*=\"NewsItem_description\"]');\n  const rk = li.querySelector('[class*=\"rank_area\"] .blind');\n  const txt = e => e ? (e.innerText || e.textContent || '').replace(/\\s+/g, ' ').trim() : '';\n  return {url: a ? a.href : '', title: txt(t), views: txt(v), desc: txt(d), rank: txt(rk), order: i};\n}).filter(r => r.url && r.title)";
export const NAVER_RANKING_PRESS = "() => [...document.querySelectorAll('div.rankingnews_box')].flatMap(box => {\n  const nm = box.querySelector('.rankingnews_name');\n  const press = nm ? nm.innerText.trim() : '';\n  return [...box.querySelectorAll('ul.rankingnews_list > li')].map(li => {\n    const a = li.querySelector('a.list_title');\n    const n = li.querySelector('.list_ranking_num');\n    const tm = li.querySelector('.list_time');\n    return {press: press, url: a ? a.href : '', title: a ? (a.innerText || '').replace(/\\s+/g, ' ').trim() : '',\n            rank: n ? parseInt(n.innerText, 10) : null, time: tm ? tm.innerText.trim() : ''};\n  });\n}).filter(r => r.url && r.title)";
export const NAVER_RANKING_SECTION = "() => {\n  const grab = (root, kind) => [...root.querySelectorAll('li.sa_item')].map((li, i) => {\n    const a = li.querySelector('a.sa_text_title');\n    const s = li.querySelector('.sa_text_strong');\n    const p = li.querySelector('.sa_text_press');\n    const tm = li.querySelector('.sa_text_datetime');\n    return {kind: kind, url: a ? a.href : '', title: s ? (s.innerText || '').replace(/\\s+/g, ' ').trim() : '',\n            press: p ? p.innerText.trim() : '', time: tm ? tm.innerText.trim() : '', order: i};\n  }).filter(r => r.url && r.title);\n  const head = document.querySelector('.as_section_headline');\n  const late = document.querySelector('.section_latest_article');\n  return {headline: head ? grab(head, 'headline') : [], latest: late ? grab(late, 'latest') : []};\n}";

export const NATE_KEYWORDS = "() => [...document.querySelectorAll('.isKeyword li')].map(li => {\n  const rank = parseInt((li.querySelector('.num_rank') || {}).textContent || '0', 10);\n  const a = li.querySelector('a');\n  const kw = (li.querySelector('.txt_rank') || {}).textContent || '';\n  const fc = li.querySelector('.fc');\n  const cls = fc ? fc.className : '';\n  const change = /new/.test(cls) ? 'new' : /up/.test(cls) ? 'up' : /down/.test(cls) ? 'down' : 'same';\n  const delta = fc ? (fc.textContent || '').replace(/[^0-9]/g, '') : '';\n  return {rank: rank, keyword: kw.trim(), url: a ? a.href : '', change: change, delta: delta};\n})";
export const NATE_HOT_NEWS = "() => {\n  const out = [];\n  document.querySelectorAll('#divHotNews [id^=\"news_div\"]').forEach(div => {\n    const tab = parseInt(div.id.replace('news_div', ''), 10) || 0;\n    div.querySelectorAll('li').forEach(li => {\n      const a = li.querySelector('a[href]');\n      if (!a) return;\n      const rank = parseInt((li.querySelector('strong') || {}).textContent || '0', 10);\n      const i = li.querySelector('i');\n      out.push({tab: tab, rank: rank, title: (a.getAttribute('title') || a.textContent || '').trim(),\n                url: a.href, change: i ? i.className : ''});\n    });\n  });\n  return out;\n}";
export const NATE_PANN_LIST = "() => [...document.querySelectorAll('#pannList ol.rank > li')].map(li => {\n  const a = li.querySelector('a.link') || li.querySelector('a[href*=\"/talk/\"]');\n  const r = parseInt((li.querySelector('.num_rank') || {}).textContent || '0', 10);\n  const c = (li.querySelector('.emph') || {}).textContent || '';\n  const m = c.match(/\\((\\d+)\\)/);\n  return {rank: r, title: a ? a.textContent.trim() : '', url: a ? a.href : '', comments: m ? parseInt(m[1], 10) : null};\n})";

export const GOOGLE_TRENDS_ROWS = "() => [...document.querySelectorAll('tr[data-row-id]')].map(tr =>\n  tr.innerText.split(/\\n+/).map(s => s.trim()).filter(Boolean))";
export const GOOGLE_TRENDS_MENU_COUNTS = "() => {\n  const m = [...document.querySelectorAll('[role=\"menu\"]')].find(m => (m.getAttribute('aria-label') || '').includes('카테고리'));\n  if (!m) return {};\n  const o = {};\n  m.querySelectorAll('[data-value]').forEach(e => {\n    const t = e.innerText.split(/\\n+/).map(s => s.trim());\n    const n = parseInt(t[1], 10);\n    o[e.getAttribute('data-value')] = isNaN(n) ? 0 : n;\n  });\n  return o;\n}";

export const DAUM_ARTICLES = "() => {\n  const seen = new Set();\n  const out = [];\n  document.querySelectorAll('a[href*=\"v.daum.net/v/\"]').forEach(a => {\n    if (seen.has(a.href)) return;\n    seen.add(a.href);\n    const t = a.querySelector('.tit_txt') || a.querySelector('strong') || a;\n    out.push({url: a.href,\n              title: (t.textContent || '').replace(/\\s+/g, ' ').trim(),\n              infos: [...a.querySelectorAll('.txt_info')].map(e => e.textContent.trim())});\n  });\n  return out;\n}";
export const DAUM_TRENDS = "() => {\n  const h = [...document.querySelectorAll('h2,h3,strong')].find(e => e.textContent.trim() === '실시간 트렌드');\n  if (!h) return [];\n  let box = h.parentElement;\n  for (let i = 0; i < 5 && box; i++) {\n    const as = [...box.querySelectorAll('a')].filter(a => /\\d+위/.test(a.textContent));\n    if (as.length >= 5) return as.map(a => ({text: a.textContent.replace(/\\s+/g, ' ').trim(), href: a.href}));\n    box = box.parentElement;\n  }\n  return [];\n}";

/** 0건일 때 진단용: 링크 도메인 분포 */
export const HOST_HISTOGRAM = "() => {\n  const h = {};\n  document.querySelectorAll('a[href]').forEach(a => { try { const u = new URL(a.href); h[u.host] = (h[u.host] || 0) + 1; } catch (e) {} });\n  return Object.entries(h).sort((a, b) => b[1] - a[1]).slice(0, 12);\n}";
